apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: reddit
    component: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: post
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
    spec:
      containers:
        - image: wasapupkindockerhub/post:1.0
#        - image: chromko/post
          name: post
          env:
            - name: POST_DATABASE_HOST
              value: post-db
