---
- name: Install docker
  hosts: all
  become: true
  tasks:
    - name: Update packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [
        "ca-certificates",
        "curl",
        "gnupg",
        "lsb-release"
      ]

    - name: Add docker repo key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: "docker-ce"
        state: present

    - name: Install docker
      apt: name={{ item }} state=latest update_cache=yes
      loop: [
        "docker-ce",
        "docker-ce-cli",
        "containerd.io"
      ]

    - name: Install python3-docker
      apt:
        name: "python3-docker"
        state: "present"
        update_cache: yes
